#!/usr/bin/env python3
"""Compile the canonical `rules/` source into each skill bundle.

Source of truth is `rules/` at the repo root. Each skill listed in SKILLS gets a
self-contained copy under `<skill>/rules/` plus a compiled `<skill>/AGENTS.md`
(every rule concatenated, ordered by `rules/_sections.md`). This is the Vercel
pattern: atomic rule files + one compiled document, bundled inside the skill.

Run: `python scripts/build_skills.py` (stdlib only, no deps).
"""

from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
RULES_DIR = REPO / "rules"
SECTIONS = RULES_DIR / "_sections.md"
SKILLS = [
    REPO / "skills" / "engineering" / "engineering-refactor",
    REPO / "skills" / "engineering" / "engineering-pr-review",
]

FRONTMATTER = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
SECTION_HEADER = re.compile(r"^##\s+\d+\.\s+(.+?)\s+\(([a-z0-9-]+)\)\s*$")
RULE_LINE = re.compile(r"^-\s+`([a-z0-9-]+)`\s+—\s+(.*)$")


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Return (frontmatter dict, body) for a rule file."""
    m = FRONTMATTER.match(text)
    if not m:
        return {}, text
    fm: dict[str, str] = {}
    for line in m.group(1).splitlines():
        if ":" in line and not line.startswith(" "):
            key, _, val = line.partition(":")
            fm[key.strip()] = val.split("#", 1)[0].strip()
    return fm, text[m.end():]


def parse_sections() -> list[tuple[str, list[str]]]:
    """Return ordered [(section_title, [rule_id, ...]), ...] from _sections.md."""
    sections: list[tuple[str, list[str]]] = []
    current: list[str] | None = None
    for line in SECTIONS.read_text(encoding="utf-8").splitlines():
        hm = SECTION_HEADER.match(line)
        if hm:
            current = []
            sections.append((hm.group(1), current))
            continue
        rm = RULE_LINE.match(line)
        if rm and current is not None:
            current.append(rm.group(1))
    return sections


def bump_headings(body: str) -> str:
    """Demote markdown headings by one level so rules nest under sections."""
    out = []
    for line in body.splitlines():
        if re.match(r"^#{1,5}\s", line):
            line = "#" + line
        out.append(line)
    return "\n".join(out)


def compile_agents_md(sections: list[tuple[str, list[str]]]) -> str:
    parts = [
        "# Engineering Rules",
        "",
        "> Compiled from the atomic rule files in `rules/`. Do not edit this file by",
        "> hand — edit `rules/<id>.md` and run `python scripts/build_skills.py`.",
        "",
        "Each rule carries `applies-to` so you can tell universal rules from",
        "stack-specific ones. Rules state one standard per concern; `direction` rules",
        "mark where existing code should head.",
        "",
        "## Contents",
        "",
    ]
    for i, (title, _) in enumerate(sections, 1):
        anchor = title.lower().replace(" ", "-").replace("/", "").replace("&", "")
        parts.append(f"{i}. [{title}](#{i}-{anchor})")
    parts.append("")

    for i, (title, rule_ids) in enumerate(sections, 1):
        parts.append(f"## {i}. {title}")
        parts.append("")
        for rid in rule_ids:
            path = RULES_DIR / f"{rid}.md"
            if not path.exists():
                raise SystemExit(f"ERROR: rule '{rid}' in _sections.md has no file {path}")
            fm, body = parse_frontmatter(path.read_text(encoding="utf-8"))
            meta = " · ".join(
                f"{k}: {fm[k]}" for k in ("scope", "applies-to", "status") if k in fm
            )
            parts.append(f"<!-- rule: {rid} -->")
            if meta:
                parts.append(f"*{meta}*")
                parts.append("")
            parts.append(bump_headings(body).strip())
            parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    if not SECTIONS.exists():
        raise SystemExit(f"ERROR: missing {SECTIONS}")
    sections = parse_sections()
    declared = {rid for _, ids in sections for rid in ids}
    on_disk = {p.stem for p in RULES_DIR.glob("*.md") if not p.name.startswith("_")}
    missing = declared - on_disk
    undeclared = on_disk - declared
    if missing:
        raise SystemExit(f"ERROR: declared but no file: {sorted(missing)}")
    if undeclared:
        raise SystemExit(f"ERROR: rule files not in _sections.md: {sorted(undeclared)}")

    agents_md = compile_agents_md(sections)
    rule_files = sorted(RULES_DIR.glob("*.md"))

    for skill in SKILLS:
        if not skill.exists():
            raise SystemExit(f"ERROR: skill dir not found: {skill}")
        dest = skill / "rules"
        if dest.exists():
            shutil.rmtree(dest)
        dest.mkdir(parents=True)
        for f in rule_files:
            shutil.copy2(f, dest / f.name)
        (skill / "AGENTS.md").write_text(agents_md, encoding="utf-8")
        print(f"built {skill.name}: {len(rule_files)} files -> rules/, AGENTS.md ({agents_md.count(chr(10))} lines)")

    print(f"OK: {len(declared)} rules across {len(sections)} sections")
    return 0


if __name__ == "__main__":
    sys.exit(main())
